### PR TITLE
Make setting default template work everywhere

### PR DESCRIPTION
**Pull request by jessedp**

### CODE REVIEW

**Comment by dougK44883** [comment]
Awesome!  This has bothered me so much for so long.  While exporting, due to OCD issues, I have a variety of naming templates.  Regularly going all the way to the setting for each change...  just thanks!!

**Comment by dougK44883** [comment]
Now this is screwy.  Prior, once shows were added to export, I could change default template and previous marked exports would maintain template'd filename.

Now when I change default via "file editor" all previous exports pick up new template.  If I exit to the settings and choose default template, then prior selected exports maintain filename while newly selected get new default.

Sadly the button is still not what beneficial.  I appreciate all the hard work and time you invest in the project!

**Comment by jessedp** [comment]
Will you give [v0.3.4-beta.1](https://github.com/jessedp/tablo-tools-electron/releases/tag/v0.3.4-beta.1) a try and let me know if ti's correct or closer?

**Comment by dougK44883** [comment]
Nope.  Perhaps when I go back to 0.2.4 I can screen shot how it was if it may help explain.  In earlier versions, once a show or shows has been added to the export list, or added to the cart the filename/template for the selected never changed.

I would go to Setting - Naming.  Selecting a different default template.  Select different shows, adding the to the cart/export list.  These shows have a different filename/template than the previous selected shows.  The previously selected shows retain their filename/template.  It was possible to have exports with multiple template used when selected shows for export.  Each time you changed templates it had NO impact on the previously selected shows in the cart/export list.

Currently, every time you change default, either from file editor **or** settings every selected show in the cart/export list gets the newly chosen default template.  Likely with the 0.3.x versions, if you want to use multiple templates, you need to export shows by template allowing export to finish, clear list.  Then change template and select new list of shows and repeat as needed.

Unfortunately this negates the benefits of the upgrades in the 0.3.x path for me.  If this was "by design"... ok.  If this is something which still needs worked out - great, let me know if I can provide more input.

**Pull request merged**
